import type { MetricDashboardRow, MetricEntry } from "./types";
import { generateDemoEntries } from "./generate-demo-entries";

const id = (n: number) => `00000000-0000-0000-0000-${String(n).padStart(12, "0")}`;

export const DEMO_METRICS: MetricDashboardRow[] = [
  {
    metric_id: id(1),
    team: "Pinnacle",
    team_id: id(101),
    role: "President & Visionary",
    role_id: id(201),
    metric_name: "Free Cash Flow",
    definition: "Success = Free Cash Flow meets or exceeds target",
    owner: null,
    owner_id: null,
    department_owner: "Michelle",
    department_owner_id: id(301),
    how_to_pull: "Found in WG Scorecard",
    tier: "Tier 1",
    cadence: "monthly",
    cadence_notes: "Monthly, PNL",
    value_type: "currency",
    target_value: null,
    target_direction: "higher_is_better",
    target_label: "Meets or exceeds target",
    is_active: true,
    sort_order: 1,
    latest_actual: null,
    latest_period_end: null,
    latest_status: "pending",
  },
  {
    metric_id: id(2),
    team: "Pinnacle",
    team_id: id(101),
    role: "President & Visionary",
    role_id: id(201),
    metric_name: "ESOP Share Value",
    definition: "Annual ESOP valuation from 3rd-party firm; success = share value meets or exceeds target",
    owner: null,
    owner_id: null,
    department_owner: "Michelle",
    department_owner_id: id(301),
    how_to_pull: "Annual ESOP valuation from 3rd-party firm",
    tier: "Tier 1",
    cadence: "annual",
    cadence_notes: "Once a year share price",
    value_type: "currency",
    target_value: null,
    target_direction: "higher_is_better",
    target_label: "Meets or exceeds target",
    is_active: true,
    sort_order: 2,
    latest_actual: null,
    latest_period_end: null,
    latest_status: "pending",
  },
  {
    metric_id: id(3),
    team: "Pinnacle",
    team_id: id(101),
    role: "COO & Integrator",
    role_id: id(202),
    metric_name: "Growth milestones",
    definition: "% of agency-wide rocks completed on time, calculated quarterly",
    owner: null,
    owner_id: null,
    department_owner: "Nicole",
    department_owner_id: id(302),
    how_to_pull: "Manual",
    tier: "Tier 1",
    cadence: "quarterly",
    cadence_notes: "Manually done by Nicole",
    value_type: "percentage",
    target_value: null,
    target_direction: "higher_is_better",
    target_label: "100% on time",
    is_active: true,
    sort_order: 3,
    latest_actual: null,
    latest_period_end: null,
    latest_status: "pending",
  },
  {
    metric_id: id(4),
    team: "Pinnacle",
    team_id: id(101),
    role: "COO & Integrator",
    role_id: id(202),
    metric_name: "Meeting effectiveness",
    definition: "% of Pinnacle (L10) meetings ending with clear decisions and assigned owners",
    owner: null,
    owner_id: null,
    department_owner: "Nicole",
    department_owner_id: id(302),
    how_to_pull: "Tracked in L10 workbook",
    tier: "Tier 1",
    cadence: "quarterly",
    cadence_notes: "ELT L10 Workbook manual by Nicole",
    value_type: "percentage",
    target_value: null,
    target_direction: "higher_is_better",
    target_label: "100%",
    is_active: true,
    sort_order: 4,
    latest_actual: null,
    latest_period_end: null,
    latest_status: "pending",
  },
  {
    metric_id: id(5),
    team: "Administration",
    team_id: id(102),
    role: "VP Admin",
    role_id: id(203),
    metric_name: "Overhead",
    definition: "Agency overhead as % of AGI, measured monthly and averaged quarterly (target ≤ 60%)",
    owner: null,
    owner_id: null,
    department_owner: "Michelle",
    department_owner_id: id(301),
    how_to_pull: "Manual",
    tier: "Tier 1",
    cadence: "monthly",
    cadence_notes: "Quickbooks, quick math",
    value_type: "percentage",
    target_value: 60,
    target_direction: "lower_is_better",
    target_label: "≤ 60%",
    is_active: true,
    sort_order: 5,
    latest_actual: 57.8,
    latest_period_end: "2025-03-31",
    latest_status: "met",
  },
  {
    metric_id: id(6),
    team: "Administration",
    team_id: id(102),
    role: "VP Admin",
    role_id: id(203),
    metric_name: "Time-to-fill",
    definition: "Average number of days to fill priority roles, tracked in ELT workbook",
    owner: null,
    owner_id: null,
    department_owner: "Michelle",
    department_owner_id: id(301),
    how_to_pull: "Manual",
    tier: "Tier 1",
    cadence: "quarterly",
    cadence_notes: "Easy to calculate",
    value_type: "days",
    target_value: null,
    target_direction: "lower_is_better",
    target_label: "Minimize days",
    is_active: true,
    sort_order: 6,
    latest_actual: null,
    latest_period_end: null,
    latest_status: "pending",
  },
  {
    metric_id: id(7),
    team: "Administration",
    team_id: id(102),
    role: "VP Admin",
    role_id: id(203),
    metric_name: "Reporting accuracy",
    definition: "% of payroll, billing, and financial reporting completed on time with no material errors",
    owner: null,
    owner_id: null,
    department_owner: "Michelle",
    department_owner_id: id(301),
    how_to_pull: "Manual",
    tier: "Tier 1",
    cadence: "monthly",
    cadence_notes: "Manual, monthly, track in sheets",
    value_type: "percentage",
    target_value: 100,
    target_direction: "higher_is_better",
    target_label: "100%",
    is_active: true,
    sort_order: 7,
    latest_actual: 100,
    latest_period_end: "2025-01-31",
    latest_status: "met",
  },
  {
    metric_id: id(8),
    team: "Marketing Solutions",
    team_id: id(103),
    role: "VP Marketing",
    role_id: id(204),
    metric_name: "Method adoption",
    definition: "% of client engagements using defined methodology, based on quarterly roadmap/project audits",
    owner: null,
    owner_id: null,
    department_owner: "Chelsea",
    department_owner_id: id(303),
    how_to_pull: "How will this be tracked?",
    tier: "Tier 1",
    cadence: "quarterly",
    cadence_notes: "Look at roadmaps — manual audit",
    value_type: "percentage",
    target_value: null,
    target_direction: "higher_is_better",
    target_label: "100% adoption",
    is_active: true,
    sort_order: 8,
    latest_actual: null,
    latest_period_end: null,
    latest_status: "pending",
  },
  {
    metric_id: id(9),
    team: "Business Development",
    team_id: id(104),
    role: "VP Sales",
    role_id: id(205),
    metric_name: "AGI",
    definition: "Actual Gross Income vs. projection targets for new and existing clients",
    owner: null,
    owner_id: null,
    department_owner: "Nicole",
    department_owner_id: id(302),
    how_to_pull: "Automate from Projections",
    tier: "Tier 1",
    cadence: "monthly",
    cadence_notes: "Pull from Projections Row 297 Budget and Target",
    value_type: "currency",
    target_value: null,
    target_direction: "higher_is_better",
    target_label: "Meets projection",
    is_active: true,
    sort_order: 9,
    latest_actual: null,
    latest_period_end: null,
    latest_status: "pending",
  },
  {
    metric_id: id(10),
    team: "Business Development",
    team_id: id(104),
    role: "VP Sales",
    role_id: id(205),
    metric_name: "CSAT",
    definition: "Average client satisfaction score from HubSpot surveys (target >1.75)",
    owner: null,
    owner_id: null,
    department_owner: "Nicole",
    department_owner_id: id(302),
    how_to_pull: "From HubSpot (Manual?)",
    tier: "Tier 1",
    cadence: "monthly",
    cadence_notes: "HubSpot Report — filter CSAT and custom survey",
    value_type: "score",
    target_value: 1.75,
    target_direction: "higher_is_better",
    target_label: "> 1.75",
    is_active: true,
    sort_order: 10,
    latest_actual: 1.79,
    latest_period_end: "2025-03-31",
    latest_status: "met",
  },
  {
    metric_id: id(11),
    team: "Business Development",
    team_id: id(104),
    role: "Dir Biz Dev",
    role_id: id(206),
    metric_name: "New AGI",
    definition: "New business AGI generated vs. budget",
    owner: null,
    owner_id: null,
    department_owner: "Nicole",
    department_owner_id: id(302),
    how_to_pull: "Automate from Projections",
    tier: "Tier 1",
    cadence: "monthly",
    cadence_notes: "Projections New business budget row 299",
    value_type: "currency",
    target_value: null,
    target_direction: "higher_is_better",
    target_label: "Meets budget",
    is_active: true,
    sort_order: 11,
    latest_actual: null,
    latest_period_end: null,
    latest_status: "pending",
  },
  {
    metric_id: id(12),
    team: "Business Development",
    team_id: id(104),
    role: "Dir Biz Dev",
    role_id: id(206),
    metric_name: "Close rate",
    definition: "Program deal closing ratio from HubSpot Sales Dashboard (target >50%)",
    owner: null,
    owner_id: null,
    department_owner: "Nicole",
    department_owner_id: id(302),
    how_to_pull: "HubSpot Sales Dashboard",
    tier: "Tier 1",
    cadence: "monthly",
    cadence_notes: "Closing ratio: deals won / (won + lost)",
    value_type: "percentage",
    target_value: 50,
    target_direction: "higher_is_better",
    target_label: "> 50%",
    is_active: true,
    sort_order: 12,
    latest_actual: 52,
    latest_period_end: "2025-03-31",
    latest_status: "met",
  },
  {
    metric_id: id(13),
    team: "Client Services",
    team_id: id(105),
    role: "Strategist",
    role_id: id(207),
    metric_name: "Client AGI",
    definition: "AGI from assigned clients vs. projections",
    owner: null,
    owner_id: null,
    department_owner: "Nicole",
    department_owner_id: id(302),
    how_to_pull: "Manual or automate from Projections",
    tier: "Tier 1",
    cadence: "monthly",
    cadence_notes: "Projections client services breakdown tab",
    value_type: "currency",
    target_value: null,
    target_direction: "higher_is_better",
    target_label: "Meets projection",
    is_active: true,
    sort_order: 13,
    latest_actual: null,
    latest_period_end: null,
    latest_status: "pending",
  },
  {
    metric_id: id(14),
    team: "Client Services",
    team_id: id(105),
    role: "Strategist",
    role_id: id(207),
    metric_name: "CSAT",
    definition: "Average HubSpot satisfaction score for assigned clients (target >1.75)",
    owner: null,
    owner_id: null,
    department_owner: "Nicole",
    department_owner_id: id(302),
    how_to_pull: "HubSpot (manual)",
    tier: "Tier 1",
    cadence: "monthly",
    cadence_notes: "Segregated by strategist — create report",
    value_type: "score",
    target_value: 1.75,
    target_direction: "higher_is_better",
    target_label: "> 1.75",
    is_active: true,
    sort_order: 14,
    latest_actual: null,
    latest_period_end: null,
    latest_status: "pending",
  },
  {
    metric_id: id(15),
    team: "Client Services",
    team_id: id(105),
    role: "HubSpot Consultant",
    role_id: id(208),
    metric_name: "Project success",
    definition: "% of HubSpot projects delivered on time and within budget (target ≥ 95%)",
    owner: null,
    owner_id: null,
    department_owner: "Chelsea",
    department_owner_id: id(303),
    how_to_pull: "Productive",
    tier: "Tier 1",
    cadence: "monthly",
    cadence_notes: "Productive project tracking",
    value_type: "percentage",
    target_value: 95,
    target_direction: "higher_is_better",
    target_label: "≥ 95%",
    is_active: true,
    sort_order: 15,
    latest_actual: 97,
    latest_period_end: "2025-03-31",
    latest_status: "met",
  },
  {
    metric_id: id(16),
    team: "Marketing Solutions",
    team_id: id(103),
    role: "Dir Marketing",
    role_id: id(209),
    metric_name: "SALs",
    definition: "Number of Sales Accepted Leads per quarter (HubSpot)",
    owner: null,
    owner_id: null,
    department_owner: "Chelsea",
    department_owner_id: id(303),
    how_to_pull: "HubSpot Dashboard",
    tier: "Tier 1",
    cadence: "quarterly",
    cadence_notes: "Weidert easy",
    value_type: "number",
    target_value: null,
    target_direction: "higher_is_better",
    target_label: "Per quarter target",
    is_active: true,
    sort_order: 16,
    latest_actual: null,
    latest_period_end: null,
    latest_status: "pending",
  },
  {
    metric_id: id(17),
    team: "Marketing Solutions",
    team_id: id(103),
    role: "Dir Marketing",
    role_id: id(209),
    metric_name: "Leads",
    definition: "Number of inbound leads per month (HubSpot)",
    owner: null,
    owner_id: null,
    department_owner: "Chelsea",
    department_owner_id: id(303),
    how_to_pull: "HubSpot Dashboard",
    tier: "Tier 1",
    cadence: "monthly",
    cadence_notes: "Weidert easy",
    value_type: "number",
    target_value: null,
    target_direction: "higher_is_better",
    target_label: "Monthly target",
    is_active: true,
    sort_order: 17,
    latest_actual: 156,
    latest_period_end: "2025-03-31",
    latest_status: "met",
  },
  {
    metric_id: id(18),
    team: "Marketing Solutions",
    team_id: id(103),
    role: "Dir Marketing",
    role_id: id(209),
    metric_name: "Branded search",
    definition: "Branded keyword search volume (Semrush)",
    owner: null,
    owner_id: null,
    department_owner: "Chelsea",
    department_owner_id: id(303),
    how_to_pull: "SEMRush",
    tier: "Tier 1",
    cadence: "monthly",
    cadence_notes: "Weidert easy",
    value_type: "number",
    target_value: null,
    target_direction: "higher_is_better",
    target_label: "Growth target",
    is_active: true,
    sort_order: 18,
    latest_actual: null,
    latest_period_end: null,
    latest_status: "pending",
  },
  {
    metric_id: id(19),
    team: "Marketing Solutions",
    team_id: id(103),
    role: "Dir Marketing",
    role_id: id(209),
    metric_name: "AI visibility",
    definition: "AI visibility score from Semrush",
    owner: null,
    owner_id: null,
    department_owner: "Chelsea",
    department_owner_id: id(303),
    how_to_pull: "SEMRush",
    tier: "Tier 1",
    cadence: "monthly",
    cadence_notes: "Weidert easy",
    value_type: "score",
    target_value: null,
    target_direction: "higher_is_better",
    target_label: "Improve score",
    is_active: true,
    sort_order: 19,
    latest_actual: null,
    latest_period_end: null,
    latest_status: "pending",
  },
  {
    metric_id: id(20),
    team: "Creative Services",
    team_id: id(106),
    role: "Creative Director",
    role_id: id(210),
    metric_name: "Rework",
    definition: "% of revisions beyond scope attributable to creative quality (target ≤ 5%)",
    owner: "Mike",
    owner_id: id(304),
    department_owner: "Jo",
    department_owner_id: id(305),
    how_to_pull: "Productive",
    tier: "Tier 1",
    cadence: "monthly",
    cadence_notes: "Tag in Productive: within/outside scope",
    value_type: "percentage",
    target_value: 5,
    target_direction: "lower_is_better",
    target_label: "≤ 5%",
    is_active: true,
    sort_order: 20,
    latest_actual: 3.8,
    latest_period_end: "2025-03-31",
    latest_status: "met",
  },
  {
    metric_id: id(21),
    team: "Creative Services",
    team_id: id(106),
    role: "Content Manager",
    role_id: id(211),
    metric_name: "Throughput",
    definition: "Volume of content produced per period (tracked monthly)",
    owner: "Vicki",
    owner_id: id(306),
    department_owner: "Jo",
    department_owner_id: id(305),
    how_to_pull: "Productive",
    tier: "Tier 1",
    cadence: "monthly",
    cadence_notes: "Completed Hours Estimated for content work",
    value_type: "number",
    target_value: null,
    target_direction: "higher_is_better",
    target_label: "Monthly volume",
    is_active: true,
    sort_order: 21,
    latest_actual: null,
    latest_period_end: null,
    latest_status: "pending",
  },
  {
    metric_id: id(22),
    team: "Web Dev",
    team_id: id(107),
    role: "Web Developer",
    role_id: id(212),
    metric_name: "Utilization",
    definition: "Billable utilization rate vs. target",
    owner: "Robert",
    owner_id: id(307),
    department_owner: "Jo",
    department_owner_id: id(305),
    how_to_pull: "Productive",
    tier: "Tier 1",
    cadence: "monthly",
    cadence_notes: "Expected billable hours by person in Productive",
    value_type: "percentage",
    target_value: null,
    target_direction: "higher_is_better",
    target_label: "Meets utilization target",
    is_active: true,
    sort_order: 22,
    latest_actual: 81,
    latest_period_end: "2025-03-31",
    latest_status: "met",
  },
];

export const DEMO_ENTRIES: MetricEntry[] = generateDemoEntries();
